---
layout: default
title: Welcome
---


```{r, echo = FALSE}
embed_png("figures/bastalogo.png", dpi = 220)
```


## Welcome {#welcome}

BaSTA is an R package that allows users to draw inference on age-specific survival and mortality patterns from capture-recapture/recovery data when a large number of individuals (or all) have missing age information (Colchero, Jones and Rebke 2012). BaSTA is based on a model developed by Colchero and Clark (2012), which extends inference from parameter estimates to the estimation of unknown (i.e. latent) times of birth and death. The package also allows testing the effect of categorical and continuous individual covariates on mortality and survival.


# Contents

<ul class="toc">
  {% include basta-nav.html %}
</ul>

<div class="exercise-box">
#### The BaSTA mailing list
<div class="box-text">
Remember to join the [BaSTA mailing list](http://lists.r-forge.r-project.org/mailman/listinfo/basta-users). You can use the list to send us bug reports, request features, or ask for advice. We will also use the list to notify BaSTA users of any updates to the package. Note that e-mails sent to the list are sent to everyone on the list.
</div>
</div>


## References {#references}

Colchero, F. and J.S. Clark (2012) Bayesian inference on age-specific survival for censored and truncated data. Journal of Animal Ecology, 81, 139-149 ([publication](http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2656.2011.01898.x/abstract)).

Colchero, F., O.R. Jones and M. Rebke (2012) BaSTA: an R package for Bayesian estimation of age-specific survival from incomplete mark-recapture/recovery data with covariates. Methods in Ecology and Evolution. 3: 466-470 ([publication](http://onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2012.00186.x/abstract))
